In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
df=datasets.load_digits()

In [5]:
plt.figure(figsize = (20,4))
for index , (image,label) in enumerate(zip(df.data[0:5] , df.target[0:5])):
  plt.subplot(1,5,index+1)
  plt.imshow(np.reshape(image , (8,8)) , cmap = plt.cm.gray)

In [6]:
x = pd.DataFrame(np.array(df.data))
y = pd.DataFrame(df.target)
print("shape of X : ", x.shape)
print("shape of Y : ",y.shape)
x.head()

shape of X :  (1797, 64)
shape of Y :  (1797, 1)

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(x)

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [9]:
x=pd.DataFrame(x)

In [10]:
x.head()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [30]:
from sklearn.decomposition import PCA
model=PCA(n_components=22)
principalcomp=model.fit_transform(x)

final_x=pd.DataFrame(principalcomp)
final_x.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,-1.259467,21.274883,-9.463055,13.014187,-7.128816,-7.440651,3.252818,2.553423,-0.581713,3.625722,...,0.854548,-3.338951,5.904431,2.742522,0.415896,-0.897743,0.719198,-3.443736,2.676027,1.052942
1,7.957612,-20.768699,4.439506,-14.893658,5.896232,-6.485590,2.126201,-4.616015,3.587539,-1.075215,...,-2.553668,-6.516747,-2.283073,-2.131637,-5.840083,4.480065,-1.950658,-5.255139,-1.218031,-4.847334
2,6.991924,-9.955987,2.958559,-12.288302,-18.126073,-4.507669,1.843246,-16.415065,0.718893,4.255021,...,0.212309,6.841685,-1.675389,-4.268559,6.742321,1.249670,0.147422,8.701652,4.958432,-2.561397
3,-15.906104,3.332464,9.824372,-12.275841,6.965119,1.089440,-1.041965,10.973867,-3.260215,6.498613,...,2.653761,-4.540751,0.791775,1.663405,-2.233226,-1.431019,2.998490,-3.914705,0.281420,3.416222
4,23.306867,4.269061,-5.675130,-13.851525,-0.358107,-2.857597,-0.720537,13.041731,-3.835375,13.414760,...,-5.288147,1.512677,-0.672490,-6.412542,-9.519115,-1.970959,-3.075037,5.031255,0.200807,5.771681

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(final_x, y, test_size=0.25)

In [32]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

C:\Users\naman\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
predict = model.predict(x_test)

In [38]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,predict)
score          #The accuracy of the model is 96.44%

0.96444444444444444

In [39]:
print('The accuracy is ' + str(100*score))

The accuracy is 96.4444444444

In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predict)

array([[44,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 32,  0,  0,  0,  0,  1,  0,  0,  1],
       [ 0,  0, 55,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 45,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0, 39,  0,  0,  0,  1,  0],
       [ 1,  0,  0,  0,  0, 45,  0,  0,  0,  3],
       [ 0,  1,  0,  0,  0,  1, 48,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 35,  0,  0],
       [ 0,  1,  0,  0,  0,  1,  0,  0, 41,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  1,  1, 50]])

In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

             precision    recall  f1-score   support

          0       0.96      1.00      0.98        44
          1       0.94      0.94      0.94        34
          2       1.00      1.00      1.00        55
          3       1.00      0.98      0.99        46
          4       1.00      0.97      0.99        40
          5       0.96      0.92      0.94        49
          6       0.98      0.94      0.96        51
          7       0.97      1.00      0.99        35
          8       0.93      0.95      0.94        43
          9       0.91      0.94      0.93        53

avg / total       0.96      0.96      0.96       450